// This file is auto-generated by @hey-api/openapi-ts

export const AdapterInstanceSchema = {
    properties: {
        adapter_name: {
            type: 'string',
            title: 'Adapter Name'
        },
        identifier: {
            type: 'string',
            title: 'Identifier'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['adapter_name', 'identifier', 'id'],
    title: 'AdapterInstance'
} as const;

export const AdapterInstanceCreateSchema = {
    properties: {
        adapter_name: {
            type: 'string',
            title: 'Adapter Name'
        },
        identifier: {
            type: 'string',
            title: 'Identifier'
        }
    },
    type: 'object',
    required: ['adapter_name', 'identifier'],
    title: 'AdapterInstanceCreate'
} as const;

export const AdapterMetaSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        version: {
            type: 'string',
            title: 'Version'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        extra: {
            additionalProperties: true,
            type: 'object',
            title: 'Extra'
        },
        type: {
            '$ref': '#/components/schemas/AdapterType'
        }
    },
    type: 'object',
    required: ['name', 'version', 'type'],
    title: 'AdapterMeta'
} as const;

export const AdapterTypeSchema = {
    type: 'string',
    enum: ['getter', 'pusher', 'processer'],
    title: 'AdapterType'
} as const;

export const AttemptSchema = {
    properties: {
        getter_timeline: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'Getter Timeline',
            description: 'A warning is triggered after getter_instance.timeline fails several consecutive times'
        }
    },
    type: 'object',
    title: 'Attempt'
} as const;

export const Body_install_package_by_whl_api_v1_pip_pkgs_whl_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_install_package_by_whl_api_v1_pip_pkgs_whl_post'
} as const;

export const CronSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        flow_id: {
            type: 'string',
            format: 'uuid',
            title: 'Flow Id'
        },
        cron: {
            type: 'string',
            title: 'Cron'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['id', 'flow_id', 'cron', 'enabled'],
    title: 'Cron'
} as const;

export const CronCreateSchema = {
    properties: {
        flow_id: {
            type: 'string',
            format: 'uuid',
            title: 'Flow Id'
        },
        cron: {
            type: 'string',
            title: 'Cron'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        }
    },
    type: 'object',
    required: ['flow_id', 'cron'],
    title: 'CronCreate'
} as const;

export const CronUpdateSchema = {
    properties: {
        cron: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cron'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        }
    },
    type: 'object',
    title: 'CronUpdate'
} as const;

export const FlowSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        nodes: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Nodes'
        }
    },
    type: 'object',
    required: ['id', 'name', 'nodes'],
    title: 'Flow'
} as const;

export const FlowCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            default: ''
        },
        nodes: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Nodes'
        }
    },
    type: 'object',
    required: ['nodes'],
    title: 'FlowCreate'
} as const;

export const FlowExecuteRequestSchema = {
    properties: {
        include_nodes: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Include Nodes'
        }
    },
    type: 'object',
    title: 'FlowExecuteRequest',
    description: 'Request body for executing a flow with optional node inclusions.'
} as const;

export const FlowInstanceSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        flow_id: {
            type: 'string',
            format: 'uuid',
            title: 'Flow Id'
        },
        status: {
            '$ref': '#/components/schemas/FlowInstanceStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'flow_id', 'status', 'created_at'],
    title: 'FlowInstance'
} as const;

export const FlowInstanceOrderSchema = {
    type: 'string',
    enum: ['created_at_desc', 'created_at_asc'],
    title: 'FlowInstanceOrder'
} as const;

export const FlowInstanceStatusSchema = {
    type: 'string',
    enum: ['waiting', 'running', 'completed', 'failed', 'cancelled'],
    title: 'FlowInstanceStatus'
} as const;

export const FlowUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        nodes: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nodes'
        }
    },
    type: 'object',
    title: 'FlowUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        message_identifier: {
            type: 'string',
            title: 'Message Identifier'
        },
        getter_name: {
            type: 'string',
            title: 'Getter Name'
        },
        ts: {
            type: 'number',
            title: 'Ts'
        },
        content: {
            '$ref': '#/components/schemas/Struct-Output'
        }
    },
    type: 'object',
    required: ['id', 'message_identifier', 'getter_name', 'ts', 'content'],
    title: 'Message'
} as const;

export const MessageCreateSchema = {
    properties: {
        message_identifier: {
            type: 'string',
            title: 'Message Identifier'
        },
        getter_name: {
            type: 'string',
            title: 'Getter Name'
        },
        ts: {
            type: 'number',
            title: 'Ts'
        },
        content: {
            '$ref': '#/components/schemas/Struct-Input'
        }
    },
    type: 'object',
    required: ['message_identifier', 'getter_name', 'ts', 'content'],
    title: 'MessageCreate'
} as const;

export const MessageOrderSchema = {
    type: 'string',
    enum: ['ts_desc', 'ts_asc', 'identifier_asc', 'identifier_desc', 'getter_name_asc', 'getter_name_desc'],
    title: 'MessageOrder'
} as const;

export const MessageUpdateSchema = {
    properties: {
        message_identifier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Identifier'
        },
        getter_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Getter Name'
        },
        ts: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ts'
        },
        content: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Struct-Input'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'MessageUpdate'
} as const;

export const NetworkSchema = {
    properties: {
        proxies: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Proxies',
            description: "Proxy configuration, e.g., {'http': 'http://...', 'https': 'https://...'}"
        }
    },
    type: 'object',
    title: 'Network'
} as const;

export const Page_AdapterInstance_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/AdapterInstance'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['items', 'total', 'limit', 'offset'],
    title: 'Page[AdapterInstance]'
} as const;

export const Page_Cron_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/Cron'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['items', 'total', 'limit', 'offset'],
    title: 'Page[Cron]'
} as const;

export const Page_FlowInstance_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/FlowInstance'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['items', 'total', 'limit', 'offset'],
    title: 'Page[FlowInstance]'
} as const;

export const Page_Flow_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/Flow'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['items', 'total', 'limit', 'offset'],
    title: 'Page[Flow]'
} as const;

export const Page_Message_Schema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/Message'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        },
        offset: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Offset'
        }
    },
    type: 'object',
    required: ['items', 'total', 'limit', 'offset'],
    title: 'Page[Message]'
} as const;

export const PipCommandResultSchema = {
    properties: {
        target: {
            type: 'string',
            title: 'Target'
        },
        output: {
            type: 'string',
            title: 'Output'
        }
    },
    type: 'object',
    required: ['target', 'output'],
    title: 'PipCommandResult'
} as const;

export const PolicySchema = {
    properties: {
        perf_merged_details: {
            type: 'boolean',
            title: 'Perf Merged Details',
            description: 'Whether to merge detailed items in performance reports',
            default: true
        },
        attempt: {
            '$ref': '#/components/schemas/Attempt',
            default: {
                getter_timeline: [5, 10, 50]
            }
        }
    },
    type: 'object',
    title: 'Policy'
} as const;

export const Struct_InputSchema = {
    properties: {
        content: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/StructText'
                    },
                    {
                        '$ref': '#/components/schemas/StructTitle'
                    },
                    {
                        '$ref': '#/components/schemas/StructImage'
                    },
                    {
                        '$ref': '#/components/schemas/StructURL'
                    }
                ]
            },
            type: 'array',
            title: 'Content'
        }
    },
    type: 'object',
    title: 'Struct'
} as const;

export const Struct_OutputSchema = {
    properties: {
        content: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/StructText'
                    },
                    {
                        '$ref': '#/components/schemas/StructTitle'
                    },
                    {
                        '$ref': '#/components/schemas/StructImage'
                    },
                    {
                        '$ref': '#/components/schemas/StructURL'
                    }
                ]
            },
            type: 'array',
            title: 'Content'
        }
    },
    type: 'object',
    title: 'Struct'
} as const;

export const StructImageSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'image'
        },
        source: {
            type: 'string',
            title: 'Source',
            description: `Image URI. Accepts valid URI including:
- Local files via 'file://' scheme (e.g., file:///path/to/image.png)
- Remote images via 'http://' or 'https://'
`
        },
        alt: {
            type: 'string',
            title: 'Alt',
            description: 'Alternative text for image',
            default: ''
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['source'],
    title: 'StructImage'
} as const;

export const StructTextSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'text'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        bold: {
            type: 'boolean',
            title: 'Bold',
            default: false
        },
        italic: {
            type: 'boolean',
            title: 'Italic',
            default: false
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['text'],
    title: 'StructText'
} as const;

export const StructTitleSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'title'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        bold: {
            type: 'boolean',
            title: 'Bold',
            default: false
        },
        italic: {
            type: 'boolean',
            title: 'Italic',
            default: false
        },
        heading: {
            type: 'integer',
            title: 'Heading',
            default: 1
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['text'],
    title: 'StructTitle'
} as const;

export const StructURLSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            default: 'url'
        },
        source: {
            type: 'string',
            title: 'Source'
        },
        title: {
            '$ref': '#/components/schemas/StructText'
        }
    },
    additionalProperties: true,
    type: 'object',
    required: ['source', 'title'],
    title: 'StructURL'
} as const;

export const SystemConfigSchema = {
    properties: {
        network: {
            '$ref': '#/components/schemas/Network',
            default: {
                proxies: {}
            }
        },
        policy: {
            '$ref': '#/components/schemas/Policy',
            default: {
                perf_merged_details: true,
                attempt: {
                    getter_timeline: [5, 10, 50]
                }
            }
        }
    },
    type: 'object',
    title: 'SystemConfig'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WarningRecipientCreateSchema = {
    properties: {
        adapter_instance_id: {
            type: 'string',
            format: 'uuid',
            title: 'Adapter Instance Id'
        }
    },
    type: 'object',
    required: ['adapter_instance_id'],
    title: 'WarningRecipientCreate'
} as const;