// This file is auto-generated by @hey-api/openapi-ts

export type AdapterInstance = {
    adapter_name: string;
    identifier: string;
    id: string;
};

export type AdapterInstanceCreate = {
    adapter_name: string;
    identifier: string;
};

export type AdapterMeta = {
    name: string;
    version: string;
    author?: (string | null);
    summary?: (string | null);
    description?: (string | null);
    url?: (string | null);
    extra?: {
        [key: string]: unknown;
    };
    type: AdapterType;
};

export type AdapterType = 'getter' | 'pusher' | 'processer';

export type Attempt = {
    /**
     * A warning is triggered after getter_instance.timeline fails several consecutive times
     */
    getter_timeline?: Array<(number)>;
};

export type Body_install_package_by_whl_api_v1_pip_pkgs_whl_post = {
    file: (Blob | File);
};

export type Cron = {
    id: string;
    flow_id: string;
    cron: string;
    enabled: boolean;
};

export type CronCreate = {
    flow_id: string;
    cron: string;
    enabled?: boolean;
};

export type CronUpdate = {
    cron?: (string | null);
    enabled?: (boolean | null);
};

export type Flow = {
    id: string;
    name: string;
    nodes: Array<(string)>;
};

export type FlowCreate = {
    name?: string;
    nodes: Array<(string)>;
};

/**
 * Request body for executing a flow with optional node exclusions.
 */
export type FlowExecuteRequest = {
    exclude_nodes?: Array<(string)>;
};

export type FlowInstance = {
    id: string;
    flow_id: string;
    status: FlowInstanceStatus;
    created_at: string;
};

export type FlowInstanceOrder = 'created_at_desc' | 'created_at_asc';

export type FlowInstanceStatus = 'waiting' | 'running' | 'completed' | 'failed' | 'cancelled';

export type FlowUpdate = {
    name?: (string | null);
    nodes?: (Array<(string)> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    id: string;
    message_identifier: string;
    getter_name: string;
    ts: number;
    content: Struct_Output;
};

export type MessageCreate = {
    message_identifier: string;
    getter_name: string;
    ts: number;
    content: Struct_Input;
};

export type MessageOrder = 'ts_desc' | 'ts_asc' | 'identifier_asc' | 'identifier_desc' | 'getter_name_asc' | 'getter_name_desc';

export type MessageUpdate = {
    message_identifier?: (string | null);
    getter_name?: (string | null);
    ts?: (number | null);
    content?: (Struct_Input | null);
};

export type Network = {
    /**
     * Proxy configuration, e.g., {'http': 'http://...', 'https': 'https://...'}
     */
    proxies?: {
        [key: string]: (string);
    };
};

export type Page_AdapterInstance_ = {
    items: Array<AdapterInstance>;
    total: number;
    limit: (number | null);
    offset: (number | null);
};

export type Page_Cron_ = {
    items: Array<Cron>;
    total: number;
    limit: (number | null);
    offset: (number | null);
};

export type Page_Flow_ = {
    items: Array<Flow>;
    total: number;
    limit: (number | null);
    offset: (number | null);
};

export type Page_FlowInstance_ = {
    items: Array<FlowInstance>;
    total: number;
    limit: (number | null);
    offset: (number | null);
};

export type Page_Message_ = {
    items: Array<Message>;
    total: number;
    limit: (number | null);
    offset: (number | null);
};

export type PipCommandResult = {
    target: string;
    output: string;
};

export type Policy = {
    /**
     * Whether to merge detailed items in performance reports
     */
    perf_merged_details?: boolean;
    attempt?: Attempt;
};

export type Struct_Input = {
    content?: Array<(StructText | StructTitle | StructImage | StructURL)>;
};

export type Struct_Output = {
    content?: Array<(StructText | StructTitle | StructImage | StructURL)>;
};

export type StructImage = {
    type?: string;
    /**
     * Image URI. Accepts valid URI including:
     * - Local files via 'file://' scheme (e.g., file:///path/to/image.png)
     * - Remote images via 'http://' or 'https://'
     *
     */
    source: string;
    /**
     * Alternative text for image
     */
    alt?: string;
    [key: string]: unknown | string;
};

export type StructText = {
    type?: string;
    text: string;
    bold?: boolean;
    italic?: boolean;
    [key: string]: unknown | string | boolean;
};

export type StructTitle = {
    type?: string;
    text: string;
    bold?: boolean;
    italic?: boolean;
    heading?: number;
    [key: string]: unknown | string | boolean | number;
};

export type StructURL = {
    type?: string;
    source: string;
    title: StructText;
    [key: string]: unknown | string | StructText;
};

export type SystemConfig = {
    network?: Network;
    policy?: Policy;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WarningRecipientCreate = {
    adapter_instance_id: string;
};

export type ListAdaptersApiV1AdaptersGetResponse = (Array<AdapterMeta>);

export type GetAdapterConfigApiV1AdaptersAdapterNameConfigGetData = {
    adapterName: string;
};

export type GetAdapterConfigApiV1AdaptersAdapterNameConfigGetResponse = ({
    [key: string]: unknown;
});

export type SetAdapterConfigApiV1AdaptersAdapterNameConfigPutData = {
    adapterName: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type SetAdapterConfigApiV1AdaptersAdapterNameConfigPutResponse = ({
    [key: string]: unknown;
});

export type GetAdapterConfigSchemaApiV1AdaptersAdapterNameConfigSchemaGetData = {
    adapterName: string;
};

export type GetAdapterConfigSchemaApiV1AdaptersAdapterNameConfigSchemaGetResponse = ({
    [key: string]: unknown;
});

export type GetAdapterInstanceConfigSchemaApiV1AdaptersAdapterNameInstanceConfigSchemaGetData = {
    adapterName: string;
};

export type GetAdapterInstanceConfigSchemaApiV1AdaptersAdapterNameInstanceConfigSchemaGetResponse = ({
    [key: string]: unknown;
});

export type CreateCronApiV1CronsPostData = {
    requestBody: CronCreate;
};

export type CreateCronApiV1CronsPostResponse = (Cron);

export type ListCronsApiV1CronsGetData = {
    cron?: (string | null);
    enabled?: (boolean | null);
    flowId?: (string | null);
    limit?: (number | null);
    offset?: (number | null);
};

export type ListCronsApiV1CronsGetResponse = (Page_Cron_);

export type UpdateCronApiV1CronsCronIdPatchData = {
    cronId: string;
    requestBody: CronUpdate;
};

export type UpdateCronApiV1CronsCronIdPatchResponse = (Cron);

export type DeleteCronApiV1CronsCronIdDeleteData = {
    cronId: string;
};

export type DeleteCronApiV1CronsCronIdDeleteResponse = (void);

export type CreateFlowApiV1FlowsPostData = {
    requestBody: FlowCreate;
};

export type CreateFlowApiV1FlowsPostResponse = (Flow);

export type ListFlowsApiV1FlowsGetData = {
    getterInstanceId?: (string | null);
    limit?: (number | null);
    offset?: (number | null);
};

export type ListFlowsApiV1FlowsGetResponse = (Page_Flow_);

export type ListFlowInstancesApiV1FlowsInstancesGetData = {
    flowId?: (string | null);
    limit?: (number | null);
    offset?: (number | null);
    order?: FlowInstanceOrder;
    status?: (FlowInstanceStatus | null);
};

export type ListFlowInstancesApiV1FlowsInstancesGetResponse = (Page_FlowInstance_);

export type GetFlowInstanceApiV1FlowsInstancesInstanceIdGetData = {
    instanceId: string;
};

export type GetFlowInstanceApiV1FlowsInstancesInstanceIdGetResponse = (FlowInstance);

export type GetFlowApiV1FlowsFlowIdGetData = {
    flowId: string;
};

export type GetFlowApiV1FlowsFlowIdGetResponse = (Flow);

export type UpdateFlowApiV1FlowsFlowIdPutData = {
    flowId: string;
    requestBody: FlowUpdate;
};

export type UpdateFlowApiV1FlowsFlowIdPutResponse = (Flow);

export type DeleteFlowApiV1FlowsFlowIdDeleteData = {
    flowId: string;
};

export type DeleteFlowApiV1FlowsFlowIdDeleteResponse = (void);

export type ExecuteFlowApiV1FlowsFlowIdExecutePostData = {
    flowId: string;
    requestBody?: (FlowExecuteRequest | null);
};

export type ExecuteFlowApiV1FlowsFlowIdExecutePostResponse = (void);

export type ListInstancesApiV1InstancesGetData = {
    adapterName?: (string | null);
    identifier?: (string | null);
    limit?: (number | null);
    offset?: (number | null);
};

export type ListInstancesApiV1InstancesGetResponse = (Page_AdapterInstance_);

export type CreateInstanceApiV1InstancesPostData = {
    requestBody: AdapterInstanceCreate;
};

export type CreateInstanceApiV1InstancesPostResponse = (AdapterInstance);

export type DeleteInstanceApiV1InstancesInstanceIdDeleteData = {
    instanceId: string;
};

export type DeleteInstanceApiV1InstancesInstanceIdDeleteResponse = (void);

export type GetInstanceConfigApiV1InstancesInstanceIdConfigGetData = {
    instanceId: string;
};

export type GetInstanceConfigApiV1InstancesInstanceIdConfigGetResponse = ({
    [key: string]: unknown;
});

export type SetInstanceConfigApiV1InstancesInstanceIdConfigPutData = {
    instanceId: string;
    requestBody: {
        [key: string]: unknown;
    };
};

export type SetInstanceConfigApiV1InstancesInstanceIdConfigPutResponse = ({
    [key: string]: unknown;
});

export type CreateMessageApiV1MessagesPostData = {
    requestBody: MessageCreate;
};

export type CreateMessageApiV1MessagesPostResponse = (Message);

export type ListMessagesApiV1MessagesGetData = {
    getterName?: (string | null);
    keywords?: (string | null);
    limit?: (number | null);
    messageIdentifier?: (string | null);
    offset?: (number | null);
    order?: MessageOrder;
    ts?: (number | null);
    tsFrom?: (number | null);
    tsTo?: (number | null);
};

export type ListMessagesApiV1MessagesGetResponse = (Page_Message_);

export type GetMessageApiV1MessagesMessageIdGetData = {
    messageId: string;
};

export type GetMessageApiV1MessagesMessageIdGetResponse = (Message);

export type DeleteMessageApiV1MessagesMessageIdDeleteData = {
    messageId: string;
};

export type DeleteMessageApiV1MessagesMessageIdDeleteResponse = (void);

export type UpdateMessageApiV1MessagesMessageIdPatchData = {
    messageId: string;
    requestBody: MessageUpdate;
};

export type UpdateMessageApiV1MessagesMessageIdPatchResponse = (Message);

export type SsoLoginApiV1OauthLoginGetResponse = (unknown);

export type SsoCallbackApiV1OauthCallbackGetResponse = (unknown);

export type InstallPackageByWhlApiV1PipPkgsWhlPostData = {
    extraIndexUrls?: (Array<(string)> | null);
    force?: boolean;
    formData: Body_install_package_by_whl_api_v1_pip_pkgs_whl_post;
    indexUrl?: (string | null);
    upgrade?: boolean;
};

export type InstallPackageByWhlApiV1PipPkgsWhlPostResponse = (PipCommandResult);

export type InstallPackageApiV1PipPkgsSpecPostData = {
    extraIndexUrls?: (Array<(string)> | null);
    force?: boolean;
    indexUrl?: (string | null);
    spec: string;
    upgrade?: boolean;
};

export type InstallPackageApiV1PipPkgsSpecPostResponse = (PipCommandResult);

export type UninstallPackageApiV1PipPkgsPackageNameDeleteData = {
    packageName: string;
    removeLoadedModules?: boolean;
};

export type UninstallPackageApiV1PipPkgsPackageNameDeleteResponse = (PipCommandResult);

export type ListIndexesApiV1PipIndexesGetData = {
    limit?: (number | null);
    offset?: (number | null);
};

export type ListIndexesApiV1PipIndexesGetResponse = (Array<(string)>);

export type GetIndexApiV1PipIndexesUrlGetData = {
    url: string;
};

export type GetIndexApiV1PipIndexesUrlGetResponse = (string);

export type AddIndexApiV1PipIndexesUrlPostData = {
    url: string;
};

export type AddIndexApiV1PipIndexesUrlPostResponse = (string);

export type DeleteIndexApiV1PipIndexesUrlDeleteData = {
    url: string;
};

export type DeleteIndexApiV1PipIndexesUrlDeleteResponse = (void);

export type ServeIndexGetResponse = (unknown);

export type ServeSpaFullPathGetData = {
    fullPath: string;
};

export type ServeSpaFullPathGetResponse = (unknown);

export type GetSystemConfigApiV1SystemConfigGetResponse = (SystemConfig);

export type SetSystemConfigApiV1SystemConfigPutData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type SetSystemConfigApiV1SystemConfigPutResponse = (SystemConfig);

export type GetSystemConfigSchemaApiV1SystemConfigSchemaGetResponse = ({
    [key: string]: unknown;
});

export type AddRecipientApiV1WarningsRecipientsPostData = {
    requestBody: WarningRecipientCreate;
};

export type AddRecipientApiV1WarningsRecipientsPostResponse = (AdapterInstance);

export type ListRecipientsApiV1WarningsRecipientsGetData = {
    limit?: (number | null);
    offset?: (number | null);
};

export type ListRecipientsApiV1WarningsRecipientsGetResponse = (Page_AdapterInstance_);

export type DeleteRecipientApiV1WarningsRecipientsAdapterInstanceIdDeleteData = {
    adapterInstanceId: string;
};

export type DeleteRecipientApiV1WarningsRecipientsAdapterInstanceIdDeleteResponse = (void);